# Generated by Django 4.2.7 on 2023-12-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rp', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('fio_rp', models.CharField(max_length=200)),
                ('id_rp', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YourModelName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
