# Generated by Django 4.2.7 on 2023-12-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryreport', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModelName',
            new_name='inventoryreportdf',
        ),
        migrations.RenameModel(
            old_name='AnotherModel',
            new_name='inventoryreporthandbook',
        ),
    ]
