# Generated by Django 5.0 on 2023-12-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryreport', '0004_forreport_inventoryreporterror_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forreport',
            name='code_fm',
        ),
        migrations.AddField(
            model_name='forreport',
            name='code_fn',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forreport',
            name='fio_rp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forreport',
            name='id_rp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forreport',
            name='name_pfm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forreport',
            name='number_pfm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryreporterror',
            name='fio_rp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryreporterror',
            name='id_rp',
            field=models.IntegerField(null=True),
        ),
    ]
