# Generated by Django 5.0 on 2023-12-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryreport', '0005_remove_forreport_code_fm_forreport_code_fn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forreport',
            name='code_fn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
