# Generated by Django 4.2.7 on 2023-12-14 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EkviringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.CharField(max_length=100, verbose_name='Дата операции')),
                ('terminal', models.CharField(max_length=100, verbose_name='Терминал')),
                ('sum_operation', models.IntegerField(verbose_name='Сумма операции')),
            ],
        ),
        migrations.CreateModel(
            name='EkviringData_enriched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField(verbose_name='ДАТАОПЕРАЦИИ')),
                ('terminal', models.BigIntegerField(verbose_name='ТЕРМИНАЛ')),
                ('sum_operation', models.IntegerField(verbose_name='СУММАОПЕРАЦИИ')),
                ('TID', models.CharField(max_length=255, verbose_name='TID')),
                ('name_rp', models.TextField(verbose_name='name_rp')),
                ('pfm', models.TextField(verbose_name='pfm')),
                ('fio_rp', models.TextField(verbose_name='fio_rp')),
                ('id_rp', models.TextField(verbose_name='id_rp')),
                ('id_x', models.TextField(verbose_name='id_x')),
                ('id_y', models.TextField(verbose_name='id_y')),
                ('street', models.TextField(verbose_name='street')),
                ('comment', models.TextField(verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_fn', models.CharField(max_length=100, verbose_name='Серийный №ФН')),
                ('date', models.CharField(max_length=100, verbose_name='Дата')),
                ('sum', models.IntegerField(verbose_name='Сумма ВВ')),
                ('created_by', models.CharField(max_length=100, verbose_name='Создал')),
                ('driver', models.CharField(blank=True, max_length=150, null=True, verbose_name='Водитель')),
                ('payment_type', models.CharField(max_length=100, verbose_name='Найм тип закр (ПЛ)')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentData_enriched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='ДАТА')),
                ('sum', models.IntegerField(verbose_name='СУММАВВ')),
                ('created_by', models.TextField(verbose_name='СОЗДАЛ')),
                ('driver', models.TextField(verbose_name='ВОДИТЕЛЬ')),
                ('payment_type', models.TextField(verbose_name='НАИМТИПЗАКР(ПЛ)')),
                ('code_fn', models.TextField(verbose_name='code_fn')),
                ('pfm', models.TextField(verbose_name='pfm')),
                ('id_x', models.TextField(verbose_name='id_x')),
                ('id_y', models.TextField(verbose_name='id_y')),
                ('name_rp', models.TextField(verbose_name='name_rp')),
            ],
        ),
        migrations.CreateModel(
            name='sprforekv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TID', models.CharField(max_length=255)),
                ('name_rp', models.TextField()),
                ('pfm', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('fio_rp', models.CharField(max_length=255)),
                ('id_rp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sprforfn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_fn', models.TextField(verbose_name='code_fn')),
                ('name_rp', models.TextField(verbose_name='name_rp')),
                ('pfm', models.TextField(verbose_name='pfm')),
            ],
        ),

    ]
