# Generated by Django 4.2.7 on 2023-12-04 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReport500',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BE', models.CharField(max_length=255)),
                ('Financial', models.CharField(max_length=255)),
                ('DocumentNumber', models.CharField(max_length=255)),
                ('MainS', models.CharField(max_length=255)),
                ('ValueIn', models.CharField(max_length=255)),
                ('CurrencyBE', models.CharField(max_length=255)),
                ('DateProcessed', models.DateField()),
                ('Processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReport500Handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BE', models.CharField(max_length=255)),
                ('Financial', models.CharField(max_length=255)),
                ('DocumentNumber', models.CharField(max_length=255)),
                ('MainS', models.CharField(max_length=255)),
                ('ValueIn', models.CharField(max_length=255)),
                ('CurrencyBE', models.CharField(max_length=255)),
                ('DateProcessed', models.DateField()),
                ('Processed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReport555',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BE', models.CharField(max_length=255)),
                ('Financial', models.CharField(max_length=255)),
                ('DocumentNumber', models.CharField(max_length=255)),
                ('MainS', models.CharField(max_length=255)),
                ('ValueIn', models.CharField(max_length=255)),
                ('CurrencyBE', models.CharField(max_length=255)),
                ('DateProcessed', models.DateField()),
                ('Processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReport555Handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BE', models.CharField(max_length=255)),
                ('Financial', models.CharField(max_length=255)),
                ('DocumentNumber', models.CharField(max_length=255)),
                ('MainS', models.CharField(max_length=255)),
                ('ValueIn', models.CharField(max_length=255)),
                ('CurrencyBE', models.CharField(max_length=255)),
                ('DateProcessed', models.DateField()),
                ('Processed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Default Department', max_length=100)),
                ('full_name', models.CharField(default='Default FIO', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
