# Generated by Django 4.2.7 on 2023-12-04 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eqvar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(blank=True, max_length=255, null=True)),
                ('dateprov', models.CharField(blank=True, max_length=255, null=True)),
                ('sumoper', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eqvarkrym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POS', models.CharField(blank=True, max_length=255, null=True)),
                ('TransactionDate', models.CharField(blank=True, max_length=255, null=True)),
                ('TransactionAmount', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EqvarSap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumberFN', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.CharField(blank=True, max_length=255, null=True)),
                ('Sum', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('Driver', models.CharField(blank=True, max_length=255, null=True)),
                ('PaymentType', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Default Department', max_length=100)),
                ('full_name', models.CharField(default='Default FIO', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
