# Generated by Django 4.2.7 on 2023-12-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equatingreport', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryReport500',
        ),
        migrations.DeleteModel(
            name='InventoryReport500Handbook',
        ),
        migrations.DeleteModel(
            name='InventoryReport555',
        ),
        migrations.DeleteModel(
            name='InventoryReport555Handbook',
        ),
    ]
